[files]
extend-exclude = [
    "ACCESSIBILITE.md",
    "ARCHITECTURE.md",
    "COMMANDES.md",
    "README.md",
    "SECURITE.md",
    "albert-code.sh",
    "albert-code.bat",
]

[default]
extend-ignore-re = ["(?m)^.*(#|//)\\s*typos:disable-line$", "datas"]

[default.extend-words]
iterm = "iterm"
ITERM = "ITERM"
asend = "asend"
ype = "ype"
