#!/usr/bin/env bash
# Install albert-code configured for the Albert API (uses a local Python venv).
# Usage:
#   curl -sSL <raw-url>/scripts/install-albert.sh | bash
#   # or, to pass the key directly:
#   curl -sSL <raw-url>/scripts/install-albert.sh | bash -s -- --api-key YOUR_KEY
set -euo pipefail

ALBERT_CODE_HOME="${ALBERT_CODE_HOME:-$HOME/.vibe}"
INSTALL_DIR="${ALBERT_CODE_INSTALL_DIR:-$HOME/.local/share/albert-code}"
REPO_URL="${ALBERT_CODE_REPO:-https://github.com/obook/albert-code.git}"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
API_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key) API_KEY="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# 1. Check Python 3.12+
# ---------------------------------------------------------------------------
if ! command -v python3 &>/dev/null; then
  echo "Error: python3 not found. Please install Python 3.12 or higher." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. Clone or update the repo, create venv, install in editable mode
# ---------------------------------------------------------------------------
if [[ -d "$INSTALL_DIR/.git" ]]; then
  echo ">> Updating existing albert-code clone in $INSTALL_DIR..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo ">> Cloning albert-code into $INSTALL_DIR..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

echo ">> Creating Python venv and installing albert-code..."
python3 -m venv "$INSTALL_DIR/.venv"
# shellcheck disable=SC1091
source "$INSTALL_DIR/.venv/bin/activate"
pip install --upgrade --disable-pip-version-check pip >/dev/null
pip install --disable-pip-version-check -e "$INSTALL_DIR"

# ---------------------------------------------------------------------------
# 3. Write Albert config
# ---------------------------------------------------------------------------
echo ">> Configuring Albert API provider..."
mkdir -p "$ALBERT_CODE_HOME"

cat > "$ALBERT_CODE_HOME/config.toml" << 'EOF'
# Albert API configuration (auto-generated by install-albert.sh)
active_model = "qwen-coder"

[[providers]]
name = "albert"
api_base = "https://albert.api.etalab.gouv.fr/v1"
api_key_env_var = "ALBERT_API_KEY"
api_style = "openai"
backend = "generic"
force_non_streaming = true

[[models]]
name = "Qwen/Qwen3-Coder-30B-A3B-Instruct"
provider = "albert"
alias = "qwen-coder"
temperature = 0.2
input_price = 0.0
output_price = 0.0

[[models]]
name = "openai/gpt-oss-120b"
provider = "albert"
alias = "gpt-oss"
temperature = 0.2
input_price = 0.0
output_price = 0.0
EOF

# ---------------------------------------------------------------------------
# 4. Prompt for API key if not provided
# ---------------------------------------------------------------------------
if [[ -z "$API_KEY" ]]; then
  echo ""
  echo "Enter your Albert API key (from https://albert.api.etalab.gouv.fr):"
  read -rsp "> " API_KEY
  echo ""
fi

if [[ -z "$API_KEY" ]]; then
  echo "Error: no API key provided."
  exit 1
fi

# Write .env (overwrite only the ALBERT_API_KEY line)
ENV_FILE="$ALBERT_CODE_HOME/.env"
if [[ -f "$ENV_FILE" ]]; then
  # Remove old ALBERT_API_KEY line if present
  sed -i.bak '/^ALBERT_API_KEY=/d' "$ENV_FILE" && rm -f "$ENV_FILE.bak"
fi
echo "ALBERT_API_KEY=$API_KEY" >> "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo ""
echo "Done! Run '$INSTALL_DIR/albert-code.sh' to start coding with the Albert API,"
echo "or add this line to your shell rc to expose 'albert-code' globally:"
echo "    alias albert-code='$INSTALL_DIR/albert-code.sh'"
